version: '2'

services:

  keycloak:
    image: 'jboss/keycloak'
    ports:
      - '8080:8080'
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
      DB_VENDOR: 'h2'
      KEYCLOAK_IMPORT: '/tmp/keycloak/realm-example.json'
    volumes:
      - './keycloak:/tmp/keycloak'
