version: '2'

services:

  keycloak:
    image: 'jboss/keycloak'
    ports:
      - '8080:8080'
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
      DB_VENDOR: 'h2'
      KEYCLOAK_IMPORT: '/tmp/keycloak/realm-example.json'
    volumes:
      - './keycloak:/tmp/keycloak:ro'

  nginx:
    image: 'nginx:alpine'
    ports:
      - '8081:80'
    volumes:
      - './clients/javascript:/usr/share/nginx/html:ro'

  flask:
    build:
      context: './clients/python-flask'
    ports:
      - '5000:5000'
    command:
      - '--host=0.0.0.0'
